In [1]:
import tensorflow as tf

In [2]:
x = tf.Variable(0.)

In [3]:
with tf.GradientTape() as tape:
    y = 2 * x + 3

In [4]:
grad_of_y_wrt_x = tape.gradient(y, x)

In [5]:
grad_of_y_wrt_x

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [6]:
x = tf.Variable(tf.random.uniform((2, 2)))

In [7]:
x

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0.21918619, 0.8435168 ],
       [0.38318253, 0.43405223]], dtype=float32)>

In [8]:
with tf.GradientTape() as tape:
    y = 2 * x + 3

In [9]:
grad_of_y_wrt_x = tape.gradient(y, x)

In [10]:
grad_of_y_wrt_x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>

In [11]:
W = tf.Variable(tf.random.uniform((2,2)))
b = tf.Variable(tf.zeros((2,)))
x = tf.random.uniform((2, 2))

In [12]:
with tf.GradientTape() as tape:
    y = tf.matmul(x, W) + b

In [13]:
grad_of_y_wrt_W_and_b = tape.gradient(y, [W, b])

In [14]:
grad_of_y_wrt_W_and_b

[<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1.0247803, 1.0247803],
        [0.9001465, 0.9001465]], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 2.], dtype=float32)>]