In [1]:
def naive_relu(x):
    assert len(x.shape) == 2
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i,j] = max(x[i,j],0)
    return x

In [2]:
def naive_add(x, y):
    assert len(x.shape) == 2
    assert x.shape == y.shape
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[i, j]
    return x

In [3]:
import numpy as np

In [6]:
import time

x = np.random.random((20,100))
y = np.random.random((20,100))


z = x + y
z = np.maximum(z, 0.)

z

array([[1.27461066, 1.06293019, 1.20429593, ..., 1.01840209, 0.99738519,
        0.7548725 ],
       [0.18706347, 0.55667904, 0.82026285, ..., 1.30012681, 0.92142757,
        0.61334422],
       [1.11970283, 0.66966463, 0.76140102, ..., 0.74871968, 1.3819848 ,
        0.61263679],
       ...,
       [1.58752061, 0.85973946, 0.15796788, ..., 0.63774293, 0.67099791,
        0.58083547],
       [1.22125297, 0.88826038, 0.39771208, ..., 1.55638655, 1.03817877,
        1.6105702 ],
       [1.15422777, 0.72351907, 0.55775458, ..., 0.58451139, 0.68318302,
        1.16272798]])

In [10]:
t0 = time.time()
for _ in range(10000):
    z = x + y
    z = np.maximum(z, 0.)
    
print('Took: {0:.2f} s'.format(time.time() - t0))

Took: 0.02 s


In [11]:
t0 = time.time()
for _ in range(10000):
    z = naive_add(x, y)
    z = naive_relu(z)
print('Took:{0:.2f} s'.format(time.time() - t0))

Took:7.73 s


In [12]:
import numpy as np
x = np.random.random((32,10))
y = np.random.random((10,))

In [13]:
x.shape

(32, 10)

In [14]:
y.shape

(10,)

In [17]:
y

array([0.72471676, 0.46648587, 0.42391601, 0.34559739, 0.55788281,
       0.99457916, 0.5859938 , 0.85223555, 0.45482563, 0.25836849])

In [18]:
y = np.expand_dims(y, axis=0)

In [19]:
y

array([[0.72471676, 0.46648587, 0.42391601, 0.34559739, 0.55788281,
        0.99457916, 0.5859938 , 0.85223555, 0.45482563, 0.25836849]])

In [20]:
y.shape

(1, 10)

In [21]:
Y = np.concatenate([y] * 32, axis=0)

In [23]:
def naive_add_matrix_and_vector(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape[0]
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[i, j]
    return x

In [24]:
import numpy as np
x = np.random.random((64, 3, 32, 10))
y = np.random.random((32, 10))
z = np.maximum(x, y)

In [ ]:
x.shape

(64, 3, 32, 10)

In [26]:
y.shape

(32, 10)

In [27]:
z.shape

(64, 3, 32, 10)

In [29]:
x = np.random.random((32,))
y = np.random.random((32,))
z = np.dot(x, y)

In [31]:
z

6.902805639163353

In [33]:
def naive_vector_dot(x, y):
    assert len(x.shape) == 1
    assert len(y.shape) == 1
    assert x.shape[0] == y.shape[0]
    z = 0.
    for i in range(x.shape[0]):
        z += x[i] * y[i]
        return z

In [34]:
def naive_matrix_dot(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 2
    assert x.shape[1] == y.shape[0]
    z = np.zeros((x.shape[0], y.shape[1]))
    for i in range(x.shape[0]):
        for j in range(y.shape[1]):
            row_x = x[i, :]
            column_y = y[:, j]
            z[i, j] = naive_vector_dot(row_x, column_y)
    return z

In [35]:
x = np.array([[0., 1.],
             [2., 3.],
             [4., 5.]])

In [36]:
x.shape

(3, 2)

In [37]:
x = x.reshape((6, 1))

In [38]:
x

array([[0.],
       [1.],
       [2.],
       [3.],
       [4.],
       [5.]])

In [39]:
x = x.reshape((2, 3))

In [40]:
x

array([[0., 1., 2.],
       [3., 4., 5.]])

In [41]:
x = np.array([[0., 1.],
             [2., 3.],
             [4., 5.]])

In [43]:
x = x.reshape((2, 3))

In [44]:
x

array([[0., 1., 2.],
       [3., 4., 5.]])

In [45]:
x = np.zeros((300, 20))

In [46]:
x = np.transpose(x)

In [47]:
x.shape

(20, 300)