In [1]:
a = [1.0, 2.0, 1.0]

In [2]:
a[0]

1.0

In [3]:
a[2]

1.0

In [4]:
a[2] = 3.0

In [5]:
a

[1.0, 2.0, 3.0]

In [6]:
import torch

In [7]:
a = torch.ones(3)

In [8]:
a

tensor([1., 1., 1.])

In [9]:
a[1]

tensor(1.)

In [10]:
float(a[1])

1.0

In [11]:
a[2] = 2.0

In [12]:
a

tensor([1., 1., 2.])

In [13]:
points = torch.zeros(6)

In [14]:
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

In [15]:
points

tensor([4., 1., 5., 3., 2., 1.])

In [16]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])

In [17]:
points

tensor([4., 1., 5., 3., 2., 1.])

In [18]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [19]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [20]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [21]:
points.shape

torch.Size([3, 2])

In [22]:
points = torch.zeros(3, 2)

In [23]:
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [24]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [25]:
points[0, 1]

tensor(1.)

In [26]:
points[0]

tensor([4., 1.])

In [27]:
points[1:]

tensor([[5., 3.],
        [2., 1.]])

In [28]:
points[1:, :]

tensor([[5., 3.],
        [2., 1.]])

In [29]:
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [30]:
img_t = torch.randn(3, 5, 5) # shape [channels, rows, columns]

In [31]:
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [32]:
batch_t = torch.randn(2, 3, 5, 5) # shape [batch, channels, rows, columns]

In [35]:
img_gray_naive = img_t.mean(-3)

In [36]:
batch_gray_naive = batch_t.mean(-3)

In [37]:
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [42]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze(-1)

In [43]:
unsqueezed_weights

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]])

In [44]:
img_weights = (img_t * unsqueezed_weights)

In [45]:
batch_weights = (batch_t * unsqueezed_weights)

In [46]:
img_gray_weighted = img_weights.sum(-3)

In [47]:
batch_gray_weighted = batch_weights.sum(-3)

In [48]:
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [49]:
img_gray_weighted_fancy = torch.einsum('...chw, c->...hw', img_t, weights)

In [50]:
batch_gray_weighted_fancy = torch.einsum('...chw, c->...hw', batch_t, weights)

In [51]:
batch_gray_weighted_fancy.shape

torch.Size([2, 5, 5])

In [52]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])

C:\Users\admin\AppData\Local\Temp\ipykernel_7128\1901091524.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at C:\cb\pytorch_1000000000000\work\c10/core/TensorImpl.h:1761.)
  weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])


In [53]:
weights_named

tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [61]:
img_named = img_t.refine_names(..., 'channels', 'rows', 'columns')

In [62]:
print('img named:', img_named.shape, img_named.names)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')


In [58]:
img_named = img_named.rename(..., None, 'a', 'b')

In [59]:
print('img named:', img_named.shape, img_named.names)

img named: torch.Size([3, 5, 5]) (None, 'a', 'b')


In [63]:
weights_aligned = weights_named.align_as(img_named)

In [64]:
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [65]:
gray_named = (img_named * weights_aligned).sum('channels')

In [66]:
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [67]:
gray_named = (img_named[..., :3] * weights_named).sum('channels')

RuntimeError: Error when attempting to broadcast dims ['channels', 'rows', 'columns'] and dims ['channels']: dim 'columns' and dim 'channels' are at the same position from the right but do not match.

In [68]:
gray_plain = gray_named.rename(None)

In [69]:
gray_plain.shape, gray_plain.names

(torch.Size([5, 5]), (None, None))

In [70]:
double_points = torch.ones(10, 2, dtype=torch.double)

In [71]:
double_points

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)

In [72]:
short_points = torch.tensor([[1, 2], [3, 4]], dtype= torch.short)

In [73]:
short_points.dtype

torch.int16

In [74]:
double_points = torch.zeros(10, 2).double()

In [75]:
double_points = torch.zeros(10, 2).to(torch.double)

In [76]:
points_64 = torch.rand(5, dtype=torch.double)

In [77]:
points_short = points_64.to(torch.short)

In [78]:
points_short * points_64

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [79]:
points_short

tensor([0, 0, 0, 0, 0], dtype=torch.int16)

In [80]:
a = torch.ones(3,2)

In [81]:
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [82]:
a_t = torch.transpose(a, 0, 1)

In [83]:
a_t

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [84]:
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [85]:
a = torch.ones(3, 2)

In [86]:
a_t = a.transpose(0, 1)

In [87]:
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [88]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [89]:
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [90]:
points_storage = points.storage()

In [91]:
points_storage[0]

4.0

In [92]:
points.storage()[1]

1.0

In [93]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [94]:
points_storage = points.storage()

In [95]:
points_storage[0] = 2.0

In [96]:
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [97]:
a = torch.ones(3, 2)

In [98]:
a.zero_()

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [99]:
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])