In [1]:
a = [1.0, 2.0, 1.0]

In [2]:
a[0]

1.0

In [3]:
a[2]

1.0

In [4]:
a[2] = 3.0

In [5]:
a

[1.0, 2.0, 3.0]

In [6]:
import torch

In [7]:
a = torch.ones(3)

In [8]:
a

tensor([1., 1., 1.])

In [9]:
a[1]

tensor(1.)

In [10]:
float(a[1])

1.0

In [11]:
a[2] = 2.0

In [12]:
a

tensor([1., 1., 2.])

In [13]:
points = torch.zeros(6)

In [14]:
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

In [15]:
points

tensor([4., 1., 5., 3., 2., 1.])

In [16]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])

In [17]:
points

tensor([4., 1., 5., 3., 2., 1.])

In [18]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [19]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [20]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [21]:
points.shape

torch.Size([3, 2])

In [22]:
points = torch.zeros(3, 2)

In [23]:
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [24]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [25]:
points[0, 1]

tensor(1.)

In [26]:
points[0]

tensor([4., 1.])

In [27]:
points[1:]

tensor([[5., 3.],
        [2., 1.]])

In [28]:
points[1:, :]

tensor([[5., 3.],
        [2., 1.]])

In [29]:
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [30]:
img_t = torch.randn(3, 5, 5) # shape [channels, rows, columns]

In [31]:
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [32]:
batch_t = torch.randn(2, 3, 5, 5) # shape [batch, channels, rows, columns]

In [35]:
img_gray_naive = img_t.mean(-3)

In [36]:
batch_gray_naive = batch_t.mean(-3)

In [37]:
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [42]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze(-1)

In [43]:
unsqueezed_weights

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]])

In [44]:
img_weights = (img_t * unsqueezed_weights)

In [45]:
batch_weights = (batch_t * unsqueezed_weights)

In [46]:
img_gray_weighted = img_weights.sum(-3)

In [47]:
batch_gray_weighted = batch_weights.sum(-3)

In [48]:
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [49]:
img_gray_weighted_fancy = torch.einsum('...chw, c->...hw', img_t, weights)

In [50]:
batch_gray_weighted_fancy = torch.einsum('...chw, c->...hw', batch_t, weights)

In [51]:
batch_gray_weighted_fancy.shape

torch.Size([2, 5, 5])

In [52]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])

C:\Users\admin\AppData\Local\Temp\ipykernel_7128\1901091524.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at C:\cb\pytorch_1000000000000\work\c10/core/TensorImpl.h:1761.)
  weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])


In [53]:
weights_named

tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [61]:
img_named = img_t.refine_names(..., 'channels', 'rows', 'columns')

In [62]:
print('img named:', img_named.shape, img_named.names)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')


In [58]:
img_named = img_named.rename(..., None, 'a', 'b')

In [59]:
print('img named:', img_named.shape, img_named.names)

img named: torch.Size([3, 5, 5]) (None, 'a', 'b')


In [63]:
weights_aligned = weights_named.align_as(img_named)

In [64]:
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [65]:
gray_named = (img_named * weights_aligned).sum('channels')

In [66]:
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [67]:
gray_named = (img_named[..., :3] * weights_named).sum('channels')

RuntimeError: Error when attempting to broadcast dims ['channels', 'rows', 'columns'] and dims ['channels']: dim 'columns' and dim 'channels' are at the same position from the right but do not match.

In [68]:
gray_plain = gray_named.rename(None)

In [69]:
gray_plain.shape, gray_plain.names

(torch.Size([5, 5]), (None, None))

In [70]:
double_points = torch.ones(10, 2, dtype=torch.double)

In [71]:
double_points

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)

In [72]:
short_points = torch.tensor([[1, 2], [3, 4]], dtype= torch.short)

In [73]:
short_points.dtype

torch.int16

In [74]:
double_points = torch.zeros(10, 2).double()

In [75]:
double_points = torch.zeros(10, 2).to(torch.double)

In [76]:
points_64 = torch.rand(5, dtype=torch.double)

In [77]:
points_short = points_64.to(torch.short)

In [78]:
points_short * points_64

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [79]:
points_short

tensor([0, 0, 0, 0, 0], dtype=torch.int16)

In [80]:
a = torch.ones(3,2)

In [81]:
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [82]:
a_t = torch.transpose(a, 0, 1)

In [83]:
a_t

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [84]:
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [85]:
a = torch.ones(3, 2)

In [86]:
a_t = a.transpose(0, 1)

In [87]:
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [88]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [89]:
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [90]:
points_storage = points.storage()

In [91]:
points_storage[0]

4.0

In [92]:
points.storage()[1]

1.0

In [93]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [94]:
points_storage = points.storage()

In [95]:
points_storage[0] = 2.0

In [96]:
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [97]:
a = torch.ones(3, 2)

In [98]:
a.zero_()

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [99]:
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [2]:
import torch

points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [3]:
second_point = points[1]

In [4]:
second_point.storage_offset()

2

In [5]:
second_point.size()

torch.Size([2])

In [6]:
second_point.shape

torch.Size([2])

In [7]:
points.stride()

(2, 1)

In [2]:
import torch

points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [3]:
points.is_contiguous()

True

In [4]:
points_t = points.t()

In [5]:
points_t.is_contiguous()

False

In [6]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [7]:
points_t = points.t()

In [8]:
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [9]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [10]:
points_t.stride()

(1, 2)

In [11]:
points_t_cont = points_t.contiguous()

In [12]:
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [13]:
points_t_cont.stride()

(3, 1)

In [14]:
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [15]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')

In [16]:
points_gpu

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], device='cuda:0')

In [17]:
points_gpu = points.to(device='cuda')

In [18]:
points_gpu

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], device='cuda:0')

In [19]:
points = 2 * points

In [20]:
points_gpu = 2 * points.to(device='cuda')

In [21]:
points_gpu = points_gpu + 4

In [22]:
points_cpu = points_gpu.to(device='cpu')

In [23]:
points_cpu

tensor([[20.,  8.],
        [24., 16.],
        [12.,  8.]])

In [24]:
points_gpu = points.cuda()

In [26]:
points = torch.ones(3, 4)

In [27]:
points_np = points.numpy()

In [28]:
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [29]:
import numpy as np

In [30]:
points = torch.from_numpy(points_np)

In [31]:
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [34]:
points.dtype

torch.float32

In [35]:
torch.save(points, 'ourpoints.t')

In [36]:
with open('ourpoints.t', 'wb') as f:
    torch.save(points, f)

In [37]:
points = torch.load('ourpoints.t')

In [38]:
with open('ourpoints.t', 'rb') as f:
    points = torch.load(f)

In [39]:
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [41]:
import h5py

In [42]:
f = h5py.File('ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()

In [43]:
f = h5py.File('ourpoints.hdf5', 'r')

In [44]:
dset = f['coords']

In [45]:
last_points = dset[-2:]

In [46]:
last_points

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [47]:
last_points = torch.from_numpy(dset[-2:])

In [48]:
f.close()

In [49]:
last_points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [50]:
a = torch.tensor(list(range(9)))

In [51]:
a.shape

torch.Size([9])

In [53]:
a.stride()

(1,)

In [55]:
a.storage_offset()

0

In [57]:
a.storage()

 0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 9]

In [58]:
b = a.view(3,3)

In [59]:
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [60]:
id(a.storage()) == id(b.storage())

True